CREATE TABLE CLIENT (
    CLI_ID INTEGER,
    TIT_CODE VARCHAR (10),
    CLI_NOM VARCHAR (30),
    CLI_PRENOM VARCHAR (30),
    CLI_ENSEIGNE VARCHAR (50)
);

CREATE TABLE OCCUPATION (
    CHB_ID INTEGER,
    JOUR VARCHAR (10),
    CLI_ID INTEGER,
    NB_PERS INTEGER,
    RESERVE INTEGER
);